import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Miniflare } from 'miniflare';
import worker from '../dist/_worker.js';
import { sha256 } from '../src/security.mjs';
let mf,db;
const pending=[];
const env={PUBLIC_ORIGIN:'https://amariva.test',ADMIN_TOKEN:'unit-test-only-operator-password-not-a-secret',STRIPE_WEBHOOK_SECRET:'webhook-unit-test-only',STRIPE_SECRET_KEY:'sk_test_unit_test_only_not_a_credential',PAYMENT_PROVIDER:'disabled',COMMERCE_ENABLED:'false'};
before(async()=>{
 mf=new Miniflare({workers:[{name:'test',modules:true,script:'export default {fetch(){return new Response("test")}}',compatibilityDate:'2026-07-01',d1Databases:{DB:'amariva-test'}}]});
 db=await mf.getD1Database('DB');env.DB=db;
 const sql=await readFile(new URL('../migrations/0001_engine.sql',import.meta.url),'utf8');
 await db.exec(sql);
});
after(async()=>{await Promise.allSettled(pending);await mf?.dispose();});
async function request(path,{body,headers={},bindings=env,method}={}) {
 const req=new Request('https://amariva.test'+path,{method:method||(body===undefined?'GET':'POST'),headers:{...(body===undefined?{}:{'Content-Type':'application/json',Origin:'https://amariva.test'}),'cf-connecting-ip':crypto.randomUUID(),...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)});
 const response=await worker.fetch(req,bindings,{waitUntil(p){pending.push(p);},passThroughOnException(){}});
 await Promise.allSettled(pending);return response;
}
const json=async(path,opts)=>{const res=await request(path,opts);return {status:res.status,headers:res.headers,body:await res.json()};};
async function signed(event){const raw=JSON.stringify(event),t=Math.floor(Date.now()/1000);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.STRIPE_WEBHOOK_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${t}.${raw}`)))).map(v=>v.toString(16).padStart(2,'0')).join('');return request('/api/webhooks/stripe',{body:raw,headers:{'Stripe-Signature':`t=${t},v1=${sig}`}});}
async function seedOrder(id,email='customer@example.com') {
 await db.prepare('INSERT OR IGNORE INTO customers(id,email) VALUES (?,?)').bind('customer-'+email,email).run();
 await db.prepare("INSERT INTO transactions(id,customer_id,product_id,amount,currency,status,provider_session,idempotency_key) VALUES (?,?,'pricing-kit',99000,'idr','checkout',?,?)").bind(id,'customer-'+email,'cs_'+id,'key_'+id).run();
 const raw='order-access-'+id;await db.prepare("INSERT INTO access_tokens(hash,kind,subject,expires_at) VALUES (?,'order',?,?)").bind(await sha256(raw),id,Math.floor(Date.now()/1000)+3600).run();return 'amariva_access='+raw;
}
function paidEvent(id,eventId='evt_'+id){return {id:eventId,type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_'+id,metadata:{order_id:id},amount_total:9900000,currency:'idr',payment_status:'paid',payment_intent:'pi_'+id}}};}
test('major public routes render useful SSR and SEO tags',async()=>{
 for(const path of ['/','/tools','/tools/kalkulator-harga-jual','/resources','/resources/cara-menentukan-harga-jual','/resources/margin-vs-markup','/resources/cara-menghitung-bep','/resources/simulasi-diskon','/products','/products/pricing-kit','/about','/contact','/privacy','/terms','/account','/checkout','/checkout/success','/checkout/cancel','/auth/verify']) {
  const res=await request(path);assert.equal(res.status,200,path);const html=await res.text();assert.match(html,/<main id="main">/);assert.match(html,/<title>/);assert.match(html,/<link rel="canonical"/);assert.doesNotMatch(html,/registered trademark|®/);
 }
});
test('404, sitemap and robots have correct behavior',async()=>{assert.equal((await request('/missing')).status,404);assert.equal((await request('/resources/missing')).status,404);const xml=await(await request('/sitemap.xml')).text();assert.match(xml,/kalkulator-harga-jual/);assert.doesNotMatch(xml,/internal|checkout|account/);assert.match(await(await request('/robots.txt')).text(),/Disallow: \/internal/);});
test('security headers and protected routes',async()=>{const res=await request('/');assert.equal(res.headers.get('X-Frame-Options'),'DENY');assert.match(res.headers.get('Content-Security-Policy'),/frame-ancestors 'none'/);assert.equal((await request('/internal/control')).status,401);const admin=await request('/internal/control',{headers:{Authorization:'Basic '+btoa('operator:'+env.ADMIN_TOKEN)}});assert.equal(admin.status,200);assert.match(await admin.text(),/Opportunity queue/);});
test('storage missing produces explicit 503; public tools still work',async()=>{const bindings={PUBLIC_ORIGIN:env.PUBLIC_ORIGIN};const h=await json('/api/health',{bindings});assert.equal(h.status,200);assert.equal(h.body.storage,'unconfigured');const lead=await json('/api/leads',{bindings,body:{email:'test@example.com',consent:true}});assert.equal(lead.status,503);assert.equal(lead.body.code,'storage_unconfigured');assert.equal((await request('/tools/kalkulator-harga-jual',{bindings})).status,200);});
test('CSRF, malformed JSON, invalid fields and content limits',async()=>{assert.equal((await request('/api/leads',{body:{},headers:{Origin:'https://attacker.test'}})).status,403);assert.equal((await request('/api/leads',{body:'not-json'})).status,400);assert.equal((await request('/api/leads',{body:{email:'bad',consent:false}})).status,400);assert.equal((await request('/api/leads',{body:{email:'a@example.com',consent:true,padding:'x'.repeat(70000)}})).status,413);});
test('email capture is persistent, consented, attributed, and deduplicated',async()=>{for(let i=0;i<2;i++){const r=await json('/api/leads',{body:{email:'Lead@Example.com',consent:true,source:'search',campaign:'pricing'}});assert.equal(r.status,201);}const lead=await db.prepare("SELECT * FROM leads WHERE email='lead@example.com'").first();assert.equal(lead.source,'search');assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM events WHERE name='lead_created'").first()).n,1);});
test('event intake requires consent and cannot forge purchase/revenue',async()=>{const b={id:crypto.randomUUID(),sessionId:crypto.randomUUID(),name:'page_view',page:'/',consent:true,source:'search'};assert.equal((await json('/api/events',{body:{...b,consent:false}})).status,400);assert.equal((await json('/api/events',{body:{...b,name:'purchase'}})).status,400);assert.equal((await json('/api/events',{body:{...b,page:'/internal/control'}})).status,400);for(let i=0;i<2;i++)assert.equal((await json('/api/events',{body:b})).status,202);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM events WHERE id=?').bind(b.id).first()).n,1);});
test('tool events have reusable persisted session status',async()=>{const sessionId=crypto.randomUUID();for(const name of ['tool_start','tool_complete','result_view'])assert.equal((await json('/api/events',{body:{id:crypto.randomUUID(),sessionId,name,page:'/tools/kalkulator-harga-jual',tool:'pricing',consent:true}})).status,202);assert.equal((await db.prepare('SELECT status FROM tool_sessions WHERE visitor_id=?').bind(sessionId).first()).status,'completed');});
test('support request stores only valid consented messages',async()=>{const r=await json('/api/contact',{body:{email:'request@example.com',topic:'privacy',message:'Please remove my lead data',consent:true}});assert.equal(r.status,201);assert.equal((await db.prepare('SELECT topic FROM support_requests WHERE id=?').bind(r.body.id).first()).topic,'privacy');});
test('rate limiting is enforced using D1, not process memory',async()=>{const headers={'cf-connecting-ip':'rate-limit-ip'};for(let i=0;i<5;i++)assert.equal((await request('/api/leads',{headers,body:{email:'rate@example.com',consent:true}})).status,201);assert.equal((await request('/api/leads',{headers,body:{email:'rate@example.com',consent:true}})).status,429);});
test('disabled commerce never creates an order or fake success',async()=>{const r=await json('/api/checkout',{body:{email:'checkout@example.com',terms:true,idempotencyKey:crypto.randomUUID()}});assert.equal(r.status,503);assert.equal(r.body.code,'payment_disabled');assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM transactions').first()).n,0);});
test('forged webhook is rejected',async()=>assert.equal((await request('/api/webhooks/stripe',{body:paidEvent('none'),headers:{'Stripe-Signature':'t=1,v1=bad'}})).status,400));
test('unpaid/wrong amount/wrong mode events never fulfill an order',async()=>{await seedOrder('invalid-payment');for(const patch of [{payment_status:'unpaid'},{amount_total:99000}]){const ev=paidEvent('invalid-payment','evt_invalid_'+crypto.randomUUID());Object.assign(ev.data.object,patch);const r=await signed(ev);assert.ok([200,400].includes(r.status));}const ev=paidEvent('invalid-payment','evt_wrong_mode');ev.livemode=true;assert.equal((await signed(ev)).status,400);assert.equal((await db.prepare("SELECT status FROM transactions WHERE id='invalid-payment'").first()).status,'checkout');assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM fulfillments WHERE transaction_id='invalid-payment'").first()).n,0);});
test('verified webhook payment transition is atomic and idempotent',async()=>{await seedOrder('paid-order');const ev=paidEvent('paid-order');assert.equal((await signed(ev)).status,200);assert.equal((await signed(ev)).status,200);assert.equal((await signed(paidEvent('paid-order','evt_paid_second_event'))).status,200);assert.equal((await db.prepare("SELECT status FROM transactions WHERE id='paid-order'").first()).status,'paid');assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM fulfillments WHERE transaction_id='paid-order'").first()).n,1);assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM events WHERE name='purchase' AND transaction_id='paid-order'").first()).n,1);});
test('order capabilities cannot access someone else or other orders of same email',async()=>{const cookie=await seedOrder('other-order');const orders=await json('/api/orders',{headers:{Cookie:cookie}});assert.deepEqual(orders.body.orders.map(x=>x.id),['other-order']);assert.equal((await request('/api/download/paid-order',{headers:{Cookie:cookie}})).status,403);assert.equal((await request('/api/download/paid-order')).status,401);});
test('authorized paid fulfillment delivers real private ZIP only once in analytics',async()=>{const raw='download-access';await db.prepare("INSERT INTO access_tokens(hash,kind,subject,expires_at) VALUES (?,'order','paid-order',?)").bind(await sha256(raw),Math.floor(Date.now()/1000)+3600).run();for(let i=0;i<2;i++){const res=await request('/api/download/paid-order',{headers:{Cookie:'amariva_access='+raw}});assert.equal(res.status,200);assert.equal(res.headers.get('Content-Type'),'application/zip');const bytes=new Uint8Array(await res.arrayBuffer());assert.equal(bytes[0],80);assert.equal(bytes[1],75);assert.ok(bytes.length>5000);}assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM events WHERE name='delivery_complete' AND transaction_id='paid-order'").first()).n,1);});
test('refund amounts use rupiah and full refund revokes access',async()=>{const refund={id:'evt_partial_refund',type:'charge.refunded',livemode:false,data:{object:{payment_intent:'pi_paid-order',currency:'idr',amount_refunded:2500000}}};assert.equal((await signed(refund)).status,200);let order=await db.prepare("SELECT * FROM transactions WHERE id='paid-order'").first();assert.equal(order.refunded_amount,25000);assert.equal(order.status,'paid');refund.id='evt_full_refund';refund.data.object.amount_refunded=9900000;assert.equal((await signed(refund)).status,200);assert.equal((await db.prepare("SELECT status FROM transactions WHERE id='paid-order'").first()).status,'refunded');assert.equal((await request('/api/download/paid-order',{headers:{Cookie:'amariva_access=download-access'}})).status,403);});
test('email verification token is hashed, single use, and grants account scope',async()=>{const raw='magic-unit-test';await db.prepare("INSERT INTO access_tokens(hash,kind,subject,expires_at) VALUES (?,'magic','customer@example.com',?)").bind(await sha256(raw),Math.floor(Date.now()/1000)+900).run();const verify=await request('/api/auth/verify',{body:{token:raw}});assert.equal(verify.status,200);const cookie=verify.headers.get('Set-Cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Lax/);const orders=await json('/api/orders',{headers:{Cookie:cookie.split(';')[0]}});assert.ok(orders.body.orders.length>=2);assert.equal((await request('/api/auth/verify',{body:{token:raw}})).status,401);assert.equal((await request('/api/auth/logout',{body:{},headers:{Cookie:cookie.split(';')[0]}})).status,200);assert.equal((await json('/api/orders',{headers:{Cookie:cookie.split(';')[0]}})).body.orders.length,0);});
