export const product = { id: 'pricing-kit', name: 'Pricing Decision Kit', price: 99000, currency: 'idr', version: '1.0', status: 'activation_pending' };
export const articles = [
 { slug: 'cara-menentukan-harga-jual', type: 'how-to', title: 'Cara menentukan harga jual tanpa menebak', description: 'Lima langkah menghitung biaya, fee, dan target volume sebelum menetapkan harga produk.', read: '6 menit', category: 'HARGA JUAL', intro: 'Harga yang terlihat kompetitif belum tentu menutup biaya. Mulai dari unit ekonomi, bukan dari harga pesaing saja.', sections: [
 ['1. Hitung biaya variabel per unit', 'Catat bahan, kemasan, ongkos produksi per unit, dan subsidi pengiriman yang Anda tanggung. Jangan masukkan sewa bulanan di sini: sewa adalah biaya tetap. Untuk layanan, masukkan waktu kerja yang dibayar per pekerjaan.'],
 ['2. Pisahkan biaya tetap per bulan', 'Sewa, gaji tetap, langganan alat, dan biaya administrasi tetap perlu dibayar meskipun penjualan nol. Gunakan periode yang sama dengan target unit penjualan.'],
 ['3. Masukkan fee penjualan', 'Fee platform 5% berarti Rp2.500 untuk harga Rp50.000. Tambahkan fee pembayaran atau komisi persentase bila berlaku. Biaya transaksi nominal tetap masuk biaya variabel, bukan kolom fee persentase.'],
 ['4. Tentukan volume yang realistis', 'Misalnya biaya variabel Rp25.000, biaya tetap Rp2.000.000, target 200 unit, fee 5%. Harga minimum = (25.000 + 2.000.000 / 200) / 0,95 = Rp36.843 setelah pembulatan ke atas. Ini baru harga impas, belum termasuk target laba atau pajak.'],
 ['5. Uji sebelum menetapkan', 'Harga Rp50.000 menghasilkan kontribusi Rp22.500 per unit. Pada 200 unit, laba operasional estimasi Rp2.500.000. Jika volume turun menjadi 80 unit, hasilnya rugi Rp200.000. Uji tiga skenario volume, lalu cek respons pelanggan dan kapasitas produksi.']
 ] },
 { slug: 'margin-vs-markup', type: 'comparison', title: 'Margin vs markup: sama-sama persen, beda makna', description: 'Contoh hitung margin dan markup agar target keuntungan tidak tertukar.', read: '4 menit', category: 'DASAR PRICING', intro: 'Markup memakai biaya sebagai pembagi. Margin memakai harga jual. Menukar keduanya bisa membuat harga Anda lebih rendah dari rencana.', sections: [
 ['Contoh yang paling sederhana', 'Biaya Rp60.000, harga jual Rp100.000. Selisih Rp40.000. Markup = 40.000 / 60.000 = 66,67%. Margin kotor = 40.000 / 100.000 = 40%. Angka ini berbeda meskipun selisih rupiahnya sama.'],
 ['Mengapa markup 30% bukan margin 30%', 'Biaya Rp100.000 dengan markup 30% menjadi harga Rp130.000. Margin hanya 30.000 / 130.000 = 23,08%. Untuk margin 30% tanpa fee, harga = 100.000 / (1 - 0,30) = Rp142.858 setelah pembulatan ke atas.'],
 ['Fee mengubah perhitungan', 'Untuk biaya Rp100.000, target kontribusi 30%, dan fee 5%, harga = 100.000 / (1 - 0,30 - 0,05) = Rp153.847. Rumus ini hanya valid jika target margin + fee kurang dari 100%. Biaya tetap belum dikurangkan.'],
 ['Gunakan istilah yang tepat', 'Kalkulator AMARIVA menampilkan margin kontribusi setelah biaya variabel dan fee, sebelum biaya tetap dan pajak. Jangan menyebutnya margin laba bersih. Saat membandingkan laporan, pastikan definisi biayanya sama.']
 ] },
 { slug: 'cara-menghitung-bep', type: 'guide', title: 'Berapa unit harus terjual untuk balik modal?', description: 'Panduan titik impas operasional, kontribusi per unit, dan contoh pembulatan BEP.', read: '5 menit', category: 'TITIK IMPAS', intro: 'Titik impas menunjukkan volume penjualan yang menutup biaya operasional pada satu periode. Ini bukan janji bahwa modal investasi awal sudah kembali.', sections: [
 ['Rumus titik impas', 'BEP unit = biaya tetap / kontribusi per unit. Kontribusi per unit = harga jual - biaya variabel - fee penjualan per unit. Bulatkan unit ke atas karena Anda umumnya tidak bisa menjual sebagian unit.'],
 ['Contoh usaha satu produk', 'Biaya tetap Rp2.000.000, harga Rp50.000, biaya variabel Rp25.000, dan fee 5% menghasilkan kontribusi Rp22.500. BEP = 2.000.000 / 22.500 = 88,89, dibulatkan menjadi 89 unit. Pada 89 unit, kontribusi Rp2.002.500 menutup biaya tetap.'],
 ['Jika kontribusi nol atau negatif', 'Tidak ada titik impas yang dapat dicapai dengan menambah penjualan pada struktur biaya tersebut. Harga harus dinaikkan atau biaya variabel dikurangi. Memperbesar volume dengan kontribusi negatif memperbesar kerugian.'],
 ['Batas penggunaan', 'Rumus ini mengasumsikan harga, biaya per unit, dan biaya tetap stabil. Untuk banyak produk, gunakan kontribusi rata-rata tertimbang sesuai bauran penjualan. Investasi awal, cicilan pokok, pajak, dan arus kas perlu analisis terpisah.'],
 ['Referensi metodologi', 'Pendekatan kontribusi dan BEP mengikuti formula yang dipublikasikan U.S. Small Business Administration. Gunakan catatan transaksi bisnis Anda sendiri untuk input, bukan rata-rata industri tanpa sumber.']
 ] },
 { slug: 'simulasi-diskon', type: 'example', title: 'Diskon 10%: berapa banyak penjualan tambahan yang dibutuhkan?', description: 'Simulasi diskon yang menghitung kontribusi, bukan sekadar omzet.', read: '4 menit', category: 'SIMULASI', intro: 'Penjualan yang lebih ramai belum tentu memberi laba lebih baik. Diskon mengambil bagian dari kontribusi, bukan hanya dari pendapatan.', sections: [
 ['Kondisi awal', 'Harga Rp50.000, biaya variabel Rp25.000, fee 5%. Kontribusi awal = Rp22.500 per unit. Menjual 100 unit menghasilkan kontribusi total Rp2.250.000 sebelum biaya tetap.'],
 ['Sesudah diskon 10%', 'Harga turun menjadi Rp45.000. Fee menjadi Rp2.250. Kontribusi baru = Rp17.750. Agar kontribusi total tetap Rp2.250.000, perlu menjual ceil(2.250.000 / 17.750) = 127 unit: setidaknya 27% lebih banyak.'],
 ['Periksa kapasitas dan biaya tambahan', 'Apakah produksi mampu memenuhi 27 unit tambahan? Apakah ada lembur, iklan, atau kemasan khusus? Tambahkan biaya ini sebelum menyimpulkan promo berhasil. Asumsi biaya tetap tidak berubah sering gagal saat kapasitas melonjak.'],
 ['Alternatif yang layak diuji', 'Coba paket bundling yang menekan biaya kemasan per unit, bonus bernilai guna dengan biaya rendah, atau diskon terbatas pada stok tertentu. Catat hipotesis, periode, kontribusi total, dan keluhan pelanggan—bukan hanya angka penjualan.']
 ] }
];
export const paths = ['/', '/tools', '/tools/kalkulator-harga-jual', '/resources', ...articles.map(a => '/resources/' + a.slug), '/products', '/products/pricing-kit', '/about', '/contact', '/privacy', '/terms'];
export const escapeHtml = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]!));
