import { Hono } from 'hono'
import { serveStatic } from 'hono/cloudflare-workers'
import api, { adminAllowed, sendNotifications } from './api'
import { Bindings, commerceReady } from './providers'
import { articles, paths, escapeHtml as e } from './content'
import { layout, home, tool, productPage, checkout, contact, legal, accountPage, breadcrumbs, articleCards, offerCTA, button } from './views'
const app = new Hono<{ Bindings: Bindings }>()
app.use('*',async(c,next)=>{
 c.header('X-Content-Type-Options','nosniff');c.header('Referrer-Policy','no-referrer');c.header('X-Frame-Options','DENY');
 c.header('Permissions-Policy','camera=(), microphone=(), geolocation=()');
 c.header('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; connect-src 'self'; frame-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");
 if(new URL(c.req.url).protocol==='https:')c.header('Strict-Transport-Security','max-age=31536000; includeSubDomains');
 if(c.req.path.startsWith('/internal')||c.req.path.startsWith('/account')||c.req.path.startsWith('/checkout')||c.req.path.startsWith('/auth')||c.req.path.startsWith('/api'))c.header('Cache-Control','no-store');
 else c.header('Cache-Control','public, max-age=0, must-revalidate');
 await next();
});
app.use('/static/*',serveStatic({root:'./public'}));
app.route('/api',api);
const siteOrigin=(c:any)=>c.env.PUBLIC_ORIGIN||new URL(c.req.url).origin;
const page=(c:any,title:string,description:string,body:string,privatePage=false,schema?:object)=>c.html(layout(title,description,c.req.path,body,siteOrigin(c),schema,privatePage));
app.get('/',c=>page(c,'AMARIVA','Tools gratis, panduan praktis, dan produk digital untuk keputusan bisnis yang lebih baik.',home()));
app.get('/tools/kalkulator-harga-jual',c=>page(c,'Kalkulator Harga Jual, Margin & BEP Gratis','Hitung margin kontribusi setelah fee, titik impas, estimasi laba, dan harga minimum. Gratis tanpa akun.',tool(),false,{'@context':'https://schema.org','@type':'WebApplication',name:'Kalkulator Harga Jual & Margin',applicationCategory:'BusinessApplication',operatingSystem:'Web',isAccessibleForFree:true,url:siteOrigin(c)+c.req.path,offers:{'@type':'Offer',price:'0',priceCurrency:'IDR'}}));
app.get('/tools',c=>page(c,'Tools bisnis gratis','Tools praktis untuk mengubah angka menjadi keputusan bisnis.',`<section class="section page-intro">${breadcrumbs('Tools gratis')}<span class="eyebrow">TOOLS YANG LANGSUNG BERGUNA</span><h1>Mulai dari satu<br><em>keputusan yang lebih baik.</em></h1><p class="lead">Gratis, tanpa akun. Kami memilih satu masalah untuk diselesaikan dengan baik, bukan puluhan tool yang setengah jadi.</p><article class="featured-tool"><div class="tool-symbol" aria-hidden="true"><span>÷</span><span>×</span><span>−</span><span>+</span></div><div class="featured-copy"><span class="eyebrow">PRICING & PROFITABILITY</span><h3>Kalkulator Harga Jual & Margin</h3><p>Kontribusi per unit, titik impas, estimasi laba, dan harga minimum dalam satu perhitungan.</p></div>${button('/tools/kalkulator-harga-jual','Buka kalkulator')}</article></section>`));
app.get('/resources',c=>page(c,'Panduan bisnis praktis','Panduan harga jual, margin, markup, titik impas, dan diskon dengan contoh yang bisa dipakai.',`<section class="section page-intro">${breadcrumbs('Panduan')}<span class="eyebrow">BELAJAR UNTUK DIGUNAKAN</span><h1>Lebih memahami.<br><em>Lebih siap memutuskan.</em></h1><p class="lead">Penjelasan singkat, contoh nyata perhitungan, dan langkah berikutnya. Fokus awal: harga, margin, dan titik impas.</p><div class="resource-grid four">${articleCards()}</div></section>`));
app.get('/resources/:slug',c=>{
 const a=articles.find(a=>a.slug===c.req.param('slug'));if(!a)return c.notFound();
 const body=`<article class="section prose page-intro">${breadcrumbs(a.title)}<span class="eyebrow">${a.category}</span><h1>${a.title}</h1><p class="lead">${a.intro}</p><div class="article-meta">Tim editorial AMARIVA · ${a.read} · Ditinjau 7 Oktober 2026</div>${a.sections.map(([title,text])=>`<section><h2>${title}</h2><p>${text}</p></section>`).join('')}${a.slug==='cara-menghitung-bep'?'<p>Rujukan: <a href="https://legacy.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point" rel="noopener noreferrer">SBA — Break-even point</a>.</p>':''}<aside class="result-next"><strong>Uji dengan angka bisnis Anda.</strong><p>Gunakan kalkulator gratis untuk kontribusi, BEP, dan estimasi laba.</p></aside>${button('/tools/kalkulator-harga-jual','Buka kalkulator gratis')}<h2>Baca juga</h2><ul>${articles.filter(v=>v.slug!==a.slug).map(v=>`<li><a href="/resources/${v.slug}">${v.title}</a></li>`).join('')}</ul></article><section class="section">${offerCTA()}</section>`;
 return page(c,a.title,a.description,body,false,{'@context':'https://schema.org','@graph':[{'@type':'Article',headline:a.title,description:a.description,datePublished:'2026-10-07',dateModified:'2026-10-07',author:{'@type':'Organization',name:'AMARIVA'},mainEntityOfPage:siteOrigin(c)+c.req.path},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Beranda',item:siteOrigin(c)},{'@type':'ListItem',position:2,name:'Panduan',item:siteOrigin(c)+'/resources'},{'@type':'ListItem',position:3,name:a.title,item:siteOrigin(c)+c.req.path}]}]});
});
app.get('/products',c=>page(c,'Produk & toolkit bisnis','Produk digital untuk pekerjaan bisnis yang lebih mendalam.',`<section class="section page-intro">${breadcrumbs('Produk')}<span class="eyebrow">LEBIH DALAM, SAAT ANDA MEMBUTUHKAN</span><h1>Dari jawaban cepat<br><em>ke cara kerja yang lebih rapi.</em></h1><p class="lead">Toolkit untuk melanjutkan pekerjaan setelah tool gratis. Tidak ada katalog besar yang belum terbukti.</p><article class="featured-tool"><div class="featured-copy"><span class="pill">${commerceReady(c.env)?'TOOLKIT DIGITAL':'PENJUALAN BELUM DIBUKA'}</span><h3>Pricing Decision Kit</h3><p>Workbook skenario, checklist biaya, dan panduan pricing. Harga rencana Rp99.000, sekali beli.</p></div>${button('/products/pricing-kit','Lihat detail')}</article></section>`));
app.get('/products/pricing-kit',c=>page(c,'Pricing Decision Kit','Bandingkan skenario harga dan volume dengan workbook pricing, checklist biaya, dan panduan penggunaan.',productPage(commerceReady(c.env))));
app.get('/checkout',c=>page(c,'Checkout Pricing Decision Kit','Status dan detail pembelian toolkit AMARIVA.',checkout(commerceReady(c.env)),true));
app.get('/checkout/success',c=>page(c,'Status pembelian','Pembayaran hanya dinyatakan berhasil setelah verifikasi provider.',`<section class="section narrow page-intro"><span class="eyebrow">STATUS PEMBELIAN</span><h1>Verifikasi dulu.<br><em>Akses setelahnya.</em></h1><p class="lead">Kembali dari pembayaran bukan bukti bahwa pembayaran berhasil. Status berikut berasal dari catatan yang diverifikasi server.</p><section id="orders-panel" class="panel" aria-live="polite"><p>Memeriksa status…</p></section><p>${button('/account','Buka akses pembelian',true)}</p></section>`,true));
app.get('/checkout/cancel',c=>page(c,'Checkout dibatalkan','Anda keluar dari checkout. Periksa status order jika sempat membayar.',`<section class="section narrow page-intro"><h1>Anda keluar<br><em>dari checkout.</em></h1><p>Kami tidak menyimpulkan status pembayaran hanya dari halaman ini. Jika Anda sudah melakukan pembayaran, periksa pembelian Anda.</p>${button('/account','Periksa pembelian',true)} ${button('/checkout','Kembali ke checkout',true)}</section>`,true));
app.get('/account',c=>page(c,'Akses pembelian','Akses produk dan riwayat pembelian yang telah diverifikasi.',accountPage(),true));
app.get('/auth/verify',c=>page(c,'Konfirmasi masuk','Konfirmasi tautan email untuk mengakses pembelian.',`<section class="section narrow page-intro"><h1>Akses yang aman.<br><em>Satu langkah lagi.</em></h1><p>Tautan masuk tidak digunakan sebelum Anda menekan tombol ini.</p><form id="verify-form" class="panel"><button class="button" type="submit">Konfirmasi masuk →</button><p id="verify-status" role="status"></p></form></section>`,true));
app.get('/about',c=>page(c,'Tentang AMARIVA','AMARIVA membangun business tools untuk better work.',`<section class="section prose page-intro">${breadcrumbs('Tentang')}<span class="eyebrow">BUSINESS TOOLS FOR BETTER WORK</span><h1>Bisnis yang lebih baik<br><em>dimulai dari kejelasan.</em></h1><p class="lead">AMARIVA membuat tools gratis, panduan, produk digital, dan fondasi software yang membantu orang mengerjakan bisnis dengan lebih baik.</p><h2>Praktis sebelum kompleks.</h2><p>Kami mulai dari keputusan yang sering muncul di usaha kecil: apakah harga sudah menutup biaya, berapa unit perlu terjual, dan apakah diskon masuk akal.</p><h2>Nilai dulu, pilihan kemudian.</h2><p>Hasil tool gratis bisa digunakan tanpa akun atau pembelian. Produk berbayar harus menambahkan kedalaman, bukan mengunci jawaban dasar.</p><h2>Kepercayaan bukan dekorasi.</h2><p>Kami menjelaskan asumsi, batasan, dan status layanan. Tidak ada testimoni, angka pelanggan, atau klaim hasil bisnis yang dibuat-buat.</p>${button('/tools/kalkulator-harga-jual','Coba tool pertama')}</section>`));
app.get('/contact',c=>page(c,'Bantuan & kontak','Dukungan produk, masukan tool, dan permintaan privasi AMARIVA.',contact()));
for(const kind of ['privacy','terms'])app.get('/'+kind,c=>page(c,kind==='privacy'?'Kebijakan privasi':'Ketentuan penggunaan','Kebijakan AMARIVA dan status awal layanan.',legal(kind,c.env.SUPPORT_EMAIL,commerceReady(c.env)?{operator:c.env.LEGAL_OPERATOR!,jurisdiction:c.env.LEGAL_JURISDICTION!,refund:c.env.REFUND_POLICY!}:undefined)));
app.get('/sitemap.xml',c=>c.body(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(path=>`<url><loc>${e(siteOrigin(c)+path)}</loc><lastmod>2026-10-07</lastmod></url>`).join('')}</urlset>`,200,{'Content-Type':'application/xml; charset=utf-8'}));
app.get('/robots.txt',c=>c.text(`User-agent: *\nAllow: /\nDisallow: /internal\nDisallow: /api/\nDisallow: /account\nDisallow: /checkout\nDisallow: /auth/\nSitemap: ${siteOrigin(c)}/sitemap.xml\n`));
app.use('/internal/*',async(c,next)=>{
 c.header('X-Robots-Tag','noindex, nofollow');
 if(!(await adminAllowed(c))){c.header('WWW-Authenticate','Basic realm="AMARIVA operator", charset="UTF-8"');return c.text('Akses operator diperlukan.',401);}
 if(c.req.method==='POST' && c.req.header('Origin')!==new URL(c.req.url).origin)return c.text('Origin ditolak.',403);
 await next();
});
app.get('/internal/control',async c=>{
 if(!c.env.DB)return page(c,'Kontrol operator','Kontrol layanan AMARIVA.',`<section class="section page-intro"><h1>Production storage blocked.</h1><aside class="notice">Batas D1 akun tercapai. Tidak ada angka analytics produksi yang ditampilkan atau disimulasikan. Buat database terpisah, jalankan migration, tambahkan binding DB, lalu redeploy.</aside><p>Commerce: disabled. Public calculator: client-side, usable.</p></section>`,true);
 const db=c.env.DB;
 const [eventRows,sources,revenue,opportunities,experiments,actions,support,outbox]=await Promise.all([
 db.prepare('SELECT name,COUNT(*) AS total,COUNT(DISTINCT session_id) AS sessions FROM events WHERE created_at>? GROUP BY name').bind(Math.floor(Date.now()/1000)-30*86400).all(),
 db.prepare("SELECT source,COUNT(*) AS total FROM events WHERE name='page_view' AND created_at>? GROUP BY source ORDER BY total DESC").bind(Math.floor(Date.now()/1000)-30*86400).all(),
 db.prepare("SELECT COUNT(CASE WHEN status IN ('paid','refunded') THEN 1 END) AS purchases,COALESCE(SUM(CASE WHEN status IN ('paid','refunded') THEN amount ELSE 0 END),0) AS gross,COALESCE(SUM(refunded_amount),0) AS refunds FROM transactions").first<any>(),
 db.prepare('SELECT * FROM opportunities ORDER BY created_at DESC').all(),db.prepare('SELECT * FROM experiments ORDER BY created_at DESC').all(),db.prepare("SELECT * FROM next_actions WHERE status='open' ORDER BY created_at").all(),db.prepare("SELECT * FROM support_requests WHERE status='open' ORDER BY created_at DESC LIMIT 50").all(),db.prepare('SELECT id,status,attempts FROM notifications ORDER BY created_at DESC LIMIT 50').all()
 ]);
 const counts=Object.fromEntries(eventRows.results.map((r:any)=>[r.name,r.total]));
 const metric=(label:string,v:unknown)=>`<article class="panel"><span class="eyebrow">${label}</span><strong>${e(v)}</strong></article>`;
 const list=(title:string,rows:any[],fields:string[])=>`<section class="panel admin-list"><h2>${title}</h2>${rows.length?rows.map(row=>`<article class="order-card">${fields.map(key=>`<p><strong>${e(key)}</strong>: ${e(row[key])}</p>`).join('')}</article>`).join(''):'<p>Belum ada data.</p>'}</section>`;
 const body=`<section class="section page-intro"><span class="eyebrow">OPERATOR ONLY · 30 HARI TERAKHIR</span><h1>Learning → next action.</h1><p>Angka browser bersifat observasional dan dapat dipalsukan; revenue hanya dari transaksi terverifikasi. Tidak termasuk pengunjung yang menolak analytics. Revenue di bawah adalah lifetime, bukan window 30 hari.</p><div class="admin-metrics">${metric('PAGE VIEWS',counts.page_view||0)}${metric('TOOL START',counts.tool_start||0)}${metric('TOOL COMPLETE',counts.tool_complete||0)}${metric('RESULT VIEW',counts.result_view||0)}${metric('LEADS',counts.lead_created||0)}${metric('OFFER VIEW',counts.offer_view||0)}${metric('CHECKOUT START',counts.checkout_start||0)}${metric('PURCHASES · LIFETIME',revenue.purchases)}${metric('REVENUE · LIFETIME',new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(revenue.gross-revenue.refunds))}${metric('REFUNDS · LIFETIME',revenue.refunds)}${metric('REPEAT USE',counts.repeat_use||0)}${metric('ACTIVATION',counts.activation||0)}</div>${list('Funnel: event counts, not deduplicated people',eventRows.results,['name','total','sessions'])}${list('Sources',sources.results,['source','total'])}${list('Opportunity queue',opportunities.results,['id','cluster','demand_source','demand_note','demand_score','pain_score','intent_score','monetization_score','status'])}${list('Experiment log',experiments.results,['id','hypothesis','metric','status','result_note'])}${list('Next-action queue',actions.results,['id','title','reason','owner','status'])}${list('Support / privacy requests',support.results,['id','email','topic','message','status'])}${list('Notification outbox',outbox.results,['id','status','attempts'])}<p>Perubahan status dilakukan operator melalui D1 terautentikasi. Tidak ada endpoint admin mutasi publik.</p></section>`;
 return page(c,'Kontrol operator','Analytics dan action queue internal.',body,true);
});
app.post('/internal/notifications/retry',async c=>{await sendNotifications(c.env);return c.json({attempted:true});});
app.notFound(c=>{c.status(404);return page(c,'Halaman tidak ditemukan','Kembali ke tools dan panduan AMARIVA.',`<section class="section narrow page-intro"><span class="eyebrow">404 · HALAMAN TIDAK DITEMUKAN</span><h1>Mari kembali<br><em>ke yang berguna.</em></h1>${button('/tools','Lihat tools gratis')}</section>`,true)});
app.onError((_err,c)=>{console.error('app_request_failed');c.status(503);return c.text('Layanan sementara tidak tersedia. Silakan coba lagi.');});
export default app
